/* Variables header for application - AppBuilder 2.03  */

/* Internal Module Links */
const int ABI_terminal_dialog = 0;

/* 'terminal_dialog' Dialog link */
const int ABN_terminal_dialog = 0;
const int ABN_tty = 1;

/* 'base' Window link */
const int ABN_base = 2;
const int ABN_combo_profile = 3;
const int ABN_btn_activate = 4;
const int ABN_txt_param3 = 5;
const int ABN_combo_infusion_mode = 6;
const int ABN_txt_param1 = 7;
const int ABN_lbl_param1 = 8;
const int ABN_lbl_param2 = 9;
const int ABN_txt_param2 = 10;
const int ABN_lbl_param3 = 11;
const int ABN_btn_start_inf = 12;
const int ABN_btn_stop_inf = 13;
const int ABN_btn_lock_screen = 14;
const int ABN_lbl_drugname = 15;
const int ABN_lbl_vol_xfrd = 16;
const int ABN_lbl_syringe_max_flow = 17;
const int ABN_combo_drug = 18;
const int ABN_combo_syringe = 19;
const int ABN_txt_vol_fill = 20;
const int ABN_lbl_syringe_dia = 21;
const int ABN_lbl_syringe_vol = 22;
const int ABN_btn_start_filling = 23;
const int ABN_btn_stop_filling = 24;
const int ABN_lbl_syringe_min_flow = 25;
const int ABN_txt_dev_ip = 26;
const int ABN_txt_host_ip = 27;
const int ABN_txt_nw_port = 28;
const int ABN_btn_setip = 29;
const int ABN_combo_pin = 30;
const int ABN_txt_new_pin = 31;
const int ABN_btn_setpin = 32;
const int ABN_txt_time = 33;
const int ABN_txt_date = 34;
const int ABN_combo_ampm = 35;
const int ABN_btn_setdate = 36;
const int ABN_multi_txt_diag = 37;
const int ABN_btn_clr_log = 38;
const int ABN_btn_open_tty = 39;
const int ABN_txt_pin = 40;
const int ABN_btn_key_3 = 41;
const int ABN_btn_key_7 = 42;
const int ABN_btn_key_8 = 43;
const int ABN_btn_key_6 = 44;
const int ABN_btn_key_4 = 45;
const int ABN_btn_key_2 = 46;
const int ABN_btn_key_5 = 47;
const int ABN_btn_key_clear = 48;
const int ABN_btn_key_0 = 49;
const int ABN_btn_key_9 = 50;
const int ABN_btn_key_1 = 51;
const int ABN_btn_key_slash = 52;
const int ABN_btn_key_dash = 53;
const int ABN_btn_key_dot = 54;
const int ABN_lbl_battery = 55;
const int ABN_lbl_date = 56;
const int ABN_btn_turnoff = 57;
const int ABN_lbl_status = 58;

